# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{less-rails}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Karst Hammer", "Nicolas M\303\251rouze", "Mathieu Fosse", "Tim Harvey"]
  s.date = %q{2010-02-03}
  s.email = %q{nicolas.merouze@gmail.com}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "README.md",
     "Rakefile",
     "VERSION",
     "init.rb",
     "less-rails.gemspec",
     "lib/less-rails.rb"
  ]
  s.homepage = %q{http://github.com/yeastymobs/less-rails}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Using Less CSS Framework with Rails}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<less>, ["~> 1.2.21"])
    else
      s.add_dependency(%q<less>, ["~> 1.2.21"])
    end
  else
    s.add_dependency(%q<less>, ["~> 1.2.21"])
  end
end

